---
# tasks file for update_pacman
- name: Initialize pacman keys
  ansible.builtin.command:
    cmd: pacman-key --init

- name: Update pacman keys
  ansible.builtin.command:
    cmd: pacman-key --populate

- name: Update pacman keyring
  community.general.pacman:
    name: archlinux-keyring
    state: latest

- name: Update packages
  community.general.pacman:
    update_cache: true
    upgrade: true
  register: pacman_output

# - name: Upgrade the system using yay, only act on AUR packages.
#   kewlfft.aur.aur:
#     upgrade: yes
#     use: yay
#     aur_only: yes
#   become: yes
# #  become_user: aur_builder

- name: Reboot machine, maybe
  ansible.builtin.shell: echo "Reboot machine"
  notify: Reboot
  when: pacman_output.stdout.find('Initcpio image generation successful') != -1
