---
- hosts: localhost
  connection: local
  become: yes

  pre_tasks:
    - name: Create ssh key
      ansible.builtin.command:
        cmd: /usr/bin/ssh-keygen -f "files/{{ ansible_ssh_private_key_file }}" -N ""
        creates: "files/{{ ansible_ssh_private_key_file }}*"
      
  roles:
    - archiso

