---
- hosts: all
  become: yes

  tasks:
    - name: Configure me
      ansible.builtin.include_role:
        name: "{{ config_role }}"
      loop: "{{ config_roles }}"
      loop_control:
        loop_var: config_role
