---
- hosts: all
  become: yes

  tasks:
    - name: Set up disks, if requested
      ansible.builtin.include_role:
        name: "setup_disk"
      vars:
         disk_category: "install_disks"

    - name: Handle networking, just in case of changes
      ansible.builtin.include_role:
        name: load_x86_64
        tasks_from: network
        # TODO: Don't forget other architectures

    - name: Update pacman and keys
      ansible.builtin.include_role:
        name: "update_pacman"

    - name: Set up NFS, if requested
      ansible.builtin.include_role:
        name: "nfs"

    - name: Set up NTP; everyone needs this
      ansible.builtin.include_role:
        name: "ntp"

    - name: Configure me
      ansible.builtin.include_role:
        name: "{{ config_role }}"
      loop: "{{ config_roles }}"
      loop_control:
        loop_var: config_role
