---
- hosts: '{{ base_host }}'
  become: yes

  vars:
    - my_host: '{{ aa_host }}'

  tasks:
    - name: foo1
      ansible.builtin.debug:
        var: inventory_hostname

    - name: foo2
      ansible.builtin.debug:
        var: hostvars[my_host]

    - name: Include the x86_64 roles
      include_role:
        name: load_x86_64
      when: "ansible_architecture == 'x86_64'"

    - name: Include the raspberry pi roles
      include_role:
        name: load_rpi
      when: "ansible_architecture == 'armv7l'"
