---
- hosts: all
  become: yes

  tasks:
    - name: Include the x86_64 roles
      include_role:
        name: load_x86_64
      when: "ansible_architecture == 'x86_64'"

    - name: Include the raspberry pi roles
      include_role:
        name: load_rpi
      when: "ansible_architecture == 'armv7l'"
