---
- hosts: '{{ base_host }}'
  become: yes

  vars:
    - my_host: '{{ aa_host }}'
    - my_host_vars: '{{ hostvars[my_host] }}'
    - niclist: "{{ my_host_vars['ipa']|dict2items }}"

  tasks:
    - name: foo
      ansible.builtin.debug:
        var: my_host_vars

    - name: boo
      ansible.builtin.debug:
        var: niclist

    - name: Include the x86_64 roles
      include_role:
        name: trans_x86
      when: "ansible_architecture == 'x86_64'"

    - name: Include the raspberry pi transition role
      include_role:
        name: trans_rpi
      when: "ansible_architecture == 'armv7l'"
