---
- hosts: hannah
  connection: ssh
  remote_user: root

  vars:
    niclist: "{{ hostvars[inventory_hostname]['ipa']|dict2items }}"
    my_boottype: "{{ hostvars[inventory_hostname]['boottype'] }}"
    # disks:   "{{ hostvars[inventory_hostname]['diskinfo']|dict2items }}"

  tasks:
    - name: Handle partitions
      include_tasks: handledisks.yml

      loop: "{{ hostvars[inventory_hostname]['diskinfo']|dict2items }}"
      loop_control:
        loop_var: outer_item
      when: '"diskinfo" in hostvars[inventory_hostname]'

    # - name: Print return information from the previous task
    #   ansible.builtin.debug:
    #     var: hostvars[inventory_hostname]['diskinfo']
