---

- name: Update packages
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Install basic packages
  community.general.pacman:
    name:
      - sudo
    # extra_args: --noconfirm
    state: present

# Special case for Arch Linux for base-devel
# See: https://archlinux.org/news/switch-to-the-base-devel-meta-package-requires-manual-intervention/
- name: Install basic packages 1
  ansible.builtin.command:
    cmd: pacman --noconfirm -Syu base-devel

- name: Install basic packages 1
  community.general.pacman:
    name:
      - base-devel
    # extra_args: --noconfirm
    state: latest

- name: Set local timezone
  ansible.builtin.file:
    src: "{{ timezone }}"
    path: /etc/localtime
    state: link

# - name: Generate adjtime file
#   command: hwclock --systohc

- name: Setup locales
  block:
    - name: Configure locale.gen
      lineinfile:
        dest: /etc/locale.gen
        regexp: '{{ item }}'
        line: '{{ item }}'
      loop: "{{ locales }}"

    - name: Create locale.conf
      copy:
        content: "LANG={{ current_locale }}"
        dest: /etc/locale.conf

    - name: Generate locales
      command: locale-gen

- name: Create user group
  ansible.builtin.group:
    name: "{{ user_name }}"

- name: Create user account
  ansible.builtin.user:
    name: "{{ user_name }}"
    # password is "password"
    password: "$6$ZE1BMAFT8ZDT7aTV$fUc4cWfabmbD7lUSg6R5QmV3R/qxQHS18kyQFiDfJmksSP4winHAoZCoE7GEGo4YD9lgk.OnzqjorvnlDjuYT0"
    group: "{{ user_name }}"
    groups: wheel
    append: yes
    create_home: yes
    update_password: on_create

- name: Expire user's password
  ansible.builtin.command:
    passwd -e {{ user_name }}

- name: Create user's ssh directory
  file:
    path: /home/{{ user_name }}/.ssh
    state: directory

- name: Set mode, owner, and group on user's ssh directory
  command: "{{ item }}"
  loop:
    - chmod 0700 /home/{{ user_name }}/.ssh
    - chown {{ user_name }}:{{ user_name }} /home/{{ user_name }}/.ssh

- name: Copy over ssh keys from current Ansible controller as an authorized key
  copy:
    src: '{{ lookup("env", "HOME") }}/.ssh/'
    dest: '/home/{{ user_name }}/.ssh/'

- name: Set mode, owner, and group on user's authorized_key file
  command: "{{ item }}"
  loop:
    - chmod 0600 /home/{{ user_name }}/.ssh/authorized_keys
    - chown {{ user_name }}:{{ user_name }} /home/{{ user_name }}/.ssh/authorized_keys

- name: Give passwordless sudo access to wheel group
  copy:
    content: '%wheel ALL=(ALL) NOPASSWD: ALL'
    dest: /etc/sudoers.d/wheel
    validate: /usr/sbin/visudo --check --file=%s

- name: Start with AUR
  block:
    - name: Make ansible custom-module directory
      ansible.builtin.file:
        path: '{{ user_home }}/.ansible/plugins/modules'
        state: directory
        mode: '0777'
        owner: '{{ user_name }}'
        group: '{{ user_group }}'

    - name: get aur helper
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/kewlfft/ansible-aur/master/plugins/modules/aur.py
        dest: '{{ user_home }}/.ansible/plugins/modules/aur.py'
        mode: '0777'
        # mode: '0644'

    - name: Make AUR build user
      ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel
      become_user: root

    - name: Set up remote_tmp dir
      ansible.builtin.file:
        path: /home/aur_builder/.ansible/tmp
        state: directory
        owner: aur_builder
        group: wheel
        mode: 0755
      become_user: root

    - name: sudo for aur_builder
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur-builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        validate: 'visudo -cf %s'
      become_user: root

    - name: AUR installs
      block:
        - name: get yay
          kewlfft.aur.aur:
            use: makepkg
            name: yay
          become_user: aur_builder

  become: true
  become_user: '{{ user_name }}'

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ my_host }}{{ domain }}"
    use: systemd

