---
vars:
  ansible_host: '{{ ip_start }}.{{ base_wired_addr }}'

- name: Add group
  ansible.builtin.group:
    name: "{{ user_name }}"
    state: present

- name: Add user
  ansible.builtin.user:
    name:  "{{ user_name }"
    group: "{{ user_name }"
    create_home: yes
    append: yes
    groups: wheel
