---
- name: Prepare dir for base profile
  ansible.builtin.file:
    path: "/etc/systemd/system/netctl@{{ item.key }}.service.d"
    state: directory
    mode: '0755'

- name: Link multi-user target
  ansible.builtin.file:
    src: "/usr/lib/systemd/system/netctl@.service"
    dest: "/etc/systemd/system/multi-user.target.wants/netctl@{{ item.key }}.service"
    force: yes
    follow: False
    state: link

- name: Add netctl@ profile
  ansible.builtin.template:
    src: profile.j2
    dest: "/etc/systemd/system/netctl@{{ item.key }}.service.d/profile.conf"

- name: Copy netctl config
  ansible.builtin.template:
    src: "{{ item.value['type'] }}-config.j2"
    dest: "/etc/netctl/{{ item.value['type'] }}"

