---
- name: Set up systemd mount unit
  ansible.builtin.template:
    src: "systemd-mount.j2"
    dest: "/etc/systemd/system/{{ item.name }}.mount"

- name: Set up systemd automount unit
  ansible.builtin.template:
    src: "systemd-automount.j2"
    dest: "/etc/systemd/system/{{ item.name }}.automount"

- name: Enable and start automount unit
  ansible.builtin.systemd:
    name: "{{ item.name }}.automount"
    enabled: yes
    state: started
