---
# tasks file for nfs

- name: Handle NFS Server
  include_tasks: nfs-server.yml

  when: '"nfs_server" in host_config'

- name: Handle NFS Clients
  include_tasks: nfs-client.yml

  when: '"nfs_client" in host_config'
