---
- name: Common
  include_tasks: nfs-common.yml

- name: permit traffic in public zone for various services
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - nfs
    - mountd
    - rpc-bind
  notify: reload firewalld

- name: Set up mounts
  include_tasks: do_client.yml
  # ansible.posix.mount:
  #   src: "{{ item.host }}:{{ item.src }}"
  #   path: "{{ item.dest }}"
  #   opts: rw,sync,soft
  #   state: mounted
  #   fstype: nfs
  loop: "{{ host_config['nfs_client'] }}"
