---
- name: Query about wiping install disks
  block:
  - name: wut
    ansible.builtin.pause:
        prompt: "OK to wipe disk?"
    register: wipe_p

  - name: doit
    ansible.builtin.debug:
      msg: "Wiping disk {{ outer_item.key }}... last chance to abort"
    when: 'wipe_p.user_input|bool'

  - name: yup
    ansible.builtin.pause:
      seconds: 10

  - name: Wipe install drive and all its partitions
    ansible.builtin.command: wipefs --force --all  "{{ outer_item.key }}"
    when: 'wipe_p.user_input|bool'

  when: 'disk_category == "install_disks" and inventory_hostname != "localhost"'
#  when: 'disk_category == "install_disks"'

- name: Handle partitions
  include_tasks: handleparts.yml
  vars:
    device_name: "{{ outer_item.key }}"
    use_luks: "{{ item.value.use_luks|default('no')|bool }}"

  loop: "{{ outer_item.value|dict2items }}"
