---
# tasks file for setup_disk
- name: Handle partitions
  include_tasks: handledisks.yml

  loop: "{{ host_config[disk_category]|dict2items }}"
  loop_control:
    loop_var: outer_item
  # vars:
  #   outer_item: "{{ host_config[disk_category]|dict2items }}"
  when: 'disk_category in host_config'
