---
ipa:
  enp3s0:
    type: wired
    style: dhcp
  wlp2s0:
    type: wireless
    style: dhcp

use_luks: false
boottype: efi

config_roles:
  - pkgs_basic
  - pkgs_admin
  - emacs_config
  - my_arch_pkgs
  - nfs
  - desktop
  - pkgs_media
  - pkgs_dev
  - dotfiles

# nfs_client:
#   - name: share-data
#     host: hannah
#     src: /data
#     dest: /share/data

#disks:
#  - 
