---
ipa:
  eno1:
    type: wired
    style: dhcp

boottype: efi

use_luks: no

install_disks:
  /dev/nveme0n1:
    boot:
      number: 1
      suffix: p1
      label: gpt
      start: 0
      end:  512MB
      flags:
        - boot
        - esp
      fstype: fat32
      mount:
    root:
      number: 2
      suffix: p2
      label: gpt
      start: 512MB
      end:  100%
      opts: -F32
      fstype: btrfs
      mount: /root
      use_luks: yes

data_disks:
  /dev/sda:
     data:
      number: 1
      suffix: 1
      label: gpt
      start: 0%
      end:  90%
      fstype: btrfs
      mount: /data
     next1:
      number: 2
      suffix: 2
      label: gpt
      start: 90%
      end:  100%
      fstype: btrfs
      mount: /data/next1

  /dev/sdb:
     stuff:
      number: 1
      suffix: 1
      label: gpt
      start: 0%
      end:  90%
      fstype: btrfs
      mount: /data/stuff
     tyson:
      number: 2
      suffix: 2
      label: gpt
      start: 90%
      end:  100%
      fstype: btrfs
      mount: /data/tyson

# backup_dirs:
#   - /data

config_roles:
  - pkgs_basic
  - pkgs_admin
  - restic
  - desktop
  - pkgs_dev
  - pkgs_media
  # - my_arch_pkgs
  - dotfiles
  - emacs_config

# nfs_server:
#   - /data
