---
ipa:
  eno1:
    type: wired
    style: dhcp

boottype: efi

install_disks:
  /dev/nvme0n1:
    boot:
      number: 1
      suffix: p1
      label: gpt
      start: 0%
      end:  512MB
      flags:
        - boot
        - esp
      fstype: vfat
      mount:
    root:
      number: 2
      suffix: p2
      label: gpt
      start: 512MB
      end:  100%
      opts: -F32
      fstype: btrfs
      mount: /root

data_disks:
  /dev/sda:
     data:
      number: 1
      suffix: 1
      label: gpt
      start: 0%
      end:  100%
      fstype: btrfs
      mount: /data

config_roles:
  - pkgs_basic
  - pkgs_admin
  - restic
  - desktop
  - pkgs_dev
  - pkgs_media
  # - my_arch_pkgs
  - dotfiles
  - emacs_config
  - jellyfin
  - calibre

nfs_server:
  - /data
