---
ipa:
  enp0s31f6:
    type: wired
    style: dhcp
  wlp2s0:
    type: wireless
    style: dhcp

boot_partition_suffix: 1
root_partition_suffix: 2
boottype: efi

config_roles:
  - pkgs_basic
  - pkgs_admin
  - emacs_config
  - my_arch_pkgs
  - nfs
  - desktop
  - pkgs_media
  - pkgs_dev
  - vm
  - dotfiles

nfs_client:
  - name: share-data
    host: metatron
    src: /data
    dest: /share/data

#disks:
#  - 
