---
ipa:
  enp3s0:
    type: wired
    ip: "155.101"
  wlp2s0:
    type: wireless
    ip: "155.161"
    primary: true

boot_partition_suffix: '2'
root_partition_suffix: '3'
boottype: bios
# This file is for use by update-ip-addr.sh
wired_interface: eno1
use_wireless: yes
wireless_interface: wlo1
