---
ipa:
  eno1:
    type: wired
    style: dhcp

boottype: efi
tailscale_key_id: A

use_luks: no

install_disks:
  /dev/sda:
    boot:
      number: 1
      suffix: 1
      label: gpt
      start: 0%
      end:  512MB
      flags:
        - boot
        - esp
      fstype: vfat
      mount:
    root:
      number: 2
      suffix: 2
      label: gpt
      start: 512MB
      end:  100%
      opts: -F32
      fstype: btrfs
      mount: /root

config_roles:
  - pkgs_basic
  - pkgs_admin
  - pkgs_dev
  - vm
  # - my_arch_pkgs
  - dotfiles
  - emacs_config

nfs_client:
  - name: share-data
    host: metatron
    src: /data
    dest: /share/data
