---
- name: Create new RPI image file
  ansible.builtin.shell:
    cmd: "{{ lookup('template', 'rpi-img-pt1.sh.j2') }}"
  register: rpi_image_result

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ rpi_mount_point }}/root/.ssh"
    state: directory
    mode: '0700'

- name: Copy ssh key file to root
  ansible.builtin.copy:
    src: "{{ ansible_ssh_private_key_file }}.pub"
    dest: "{{ rpi_mount_point }}/root/.ssh/authorized_keys"
    mode: '0644'

- name: Prepare dir for wired profile
  ansible.builtin.file:
    path: "{{ rpi_mount_point }}/etc/systemd/system/netctl@wired.service.d"
    state: directory
    mode: '0755'

- name: Link multi-user target
  ansible.builtin.file:
    src: "{{ rpi_mount_point }}/usr/lib/systemd/system/netctl@.service"
    dest: "{{ rpi_mount_point }}/etc/systemd/system/multi-user.target.wants/netctl@wired.service"
    state: link

- name: Add wired netctl profile
  ansible.builtin.template:
    src: wired.j2
    dest: "{{ rpi_mount_point }}/etc/systemd/system/netctl@wired.service.d/profile.conf"

- name: Copy wired netctl profile
  ansible.builtin.template:
    src: wired.j2
    dest: "{{ rpi_mount_point }}/etc/netctl/wired"

- name: Prepare dir for wireless profile
  ansible.builtin.file:
    path: "{{ rpi_mount_point }}/etc/systemd/system/netctl@wireless.service.d"
    state: directory
    mode: '0755'

- name: Link multi-user target
  ansible.builtin.file:
    src: "{{ rpi_mount_point }}/usr/lib/systemd/system/netctl@.service"
    dest: "{{ rpi_mount_point }}/etc/systemd/system/multi-user.target.wants/netctl@wireless.service"
    state: link

- name: Add wireless netctl profile
  ansible.builtin.template:
    src: wireless.j2
    dest: "{{ rpi_mount_point }}/etc/systemd/system/netctl@wireless.service.d/profile.conf"

- name: Copy wireless netctl profile
  ansible.builtin.template:
    src: wireless.j2
    dest: "{{ rpi_mount_point }}/etc/netctl/wireless"

- name: Disable systemd-networkd service (now using netctl)
  ansible.builtin.file:
    path: "{{ rpi_mount_point }}/etc/systemd/system/multi-user.target.wants/systemd-networkd.service"
    state: absent

- name: Finish new RPI image file
  ansible.builtin.shell:
    cmd: "{{ lookup('template', 'rpi-img-pt2.sh.j2') }}"

- name: debug2
  ansible.builtin.debug:
    var: rpi_image_result.stdout_lines
