---
- name: Create new RPI image file
  ansible.builtin.shell:
    cmd: "{{ lookup('template', 'rpi-img-pt1.sh.j2') }}"
  register: rpi_image_result

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ rpi_mount_point }}/root/.ssh"
    state: directory
    mode: '0700'

- name: Copy ssh key file to root
  ansible.builtin.copy:
    src: "{{ ansible_ssh_private_key_file }}.pub"
    dest: "{{ rpi_mount_point }}/root/.ssh/authorized_keys"
    mode: '0644'

- name: Deploy base networking profiles
  include_tasks: setup_base_networking.yml
  loop:
    - wired
    - wireless

# - name: Prepare dir for wired profile
#   ansible.builtin.file:
#     path: "{{ rpi_mount_point }}/etc/systemd/system/netctl@wired.service.d"
#     state: directory
#     mode: '0755'

# - name: Link multi-user target
#   ansible.builtin.file:
#     src: "/usr/lib/systemd/system/netctl@.service"
#     dest: "{{ rpi_mount_point }}/etc/systemd/system/multi-user.target.wants/netctl@wired.service"
#     force: yes
#     follow: False
#     state: link

# - name: Add wired netctl profile
#   ansible.builtin.template:
#     src: wired-profile.j2
#     dest: "{{ rpi_mount_point }}/etc/systemd/system/netctl@wired.service.d/profile.conf"

# - name: Copy wired netctl profile
#   ansible.builtin.template:
#     src: wired.j2
#     dest: "{{ rpi_mount_point }}/etc/netctl/wired"

# - name: Prepare dir for wireless profile
#   ansible.builtin.file:
#     path: "{{ rpi_mount_point }}/etc/systemd/system/netctl@wireless.service.d"
#     state: directory
#     mode: '0755'

# - name: Link multi-user target
#   ansible.builtin.file:
#     src: "/usr/lib/systemd/system/netctl@.service"
#     dest: "{{ rpi_mount_point }}/etc/systemd/system/multi-user.target.wants/netctl@wireless.service"
#     force: yes
#     follow: False
#     state: link

# - name: Add wireless netctl profile
#   ansible.builtin.template:
#     src: wireless-profile.j2
#     dest: "{{ rpi_mount_point }}/etc/systemd/system/netctl@wireless.service.d/profile.conf"

# - name: Copy wireless netctl profile
#   ansible.builtin.template:
#     src: wireless.j2
#     dest: "{{ rpi_mount_point }}/etc/netctl/wireless"

# Removed "/etc/systemd/system/network-online.target.wants/systemd-networkd-wait-online.service".
# Removed "/etc/systemd/system/sockets.target.wants/systemd-networkd.socket".
# Removed "/etc/systemd/system/dbus-org.freedesktop.network1.service".

- name: Disable systemd-networkd service (now using netctl)
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ rpi_mount_point }}/etc/systemd/system/multi-user.target.wants/systemd-networkd.service"
    - "{{ rpi_mount_point }}/etc/systemd/system/network-online.target.wants/systemd-networkd-wait-online.service"
    - "{{ rpi_mount_point }}/etc/systemd/system/sockets.target.wants/systemd-networkd.socket"
    - "{{ rpi_mount_point }}/etc/systemd/system/dbus-org.freedesktop.network1.service"

- name: Set up system setup script
  ansible.builtin.copy:
    src: setup.sh
    dest: "{{ rpi_mount_point }}/root/"
    mode: '0544'

- name: Set up system setup service
  ansible.builtin.copy:
    src: run-aa-once-setup.service
    dest: "{{ rpi_mount_point }}/etc/systemd/system/"
    mode: '0444'

- name: Set default.target
  ansible.builtin.file:
    path: "{{ rpi_mount_point }}/etc/systemd/system/default.target.wants"
    state: directory
    mode: '0755'

- name: Link default setup target
  ansible.builtin.file:
    src: "/etc/systemd/system/run-aa-once-setup.service"
    dest: "{{ rpi_mount_point }}/etc/systemd/system/default.target.wants/run-aa-once-setup.service"
    force: yes
    follow: False
    state: link

- name: Finish new RPI image file
  ansible.builtin.shell:
    cmd: "{{ lookup('template', 'rpi-img-pt2.sh.j2') }}"

- name: debug2
  ansible.builtin.debug:
    var: rpi_image_result.stdout_lines
