---
- name: What image file?
  ansible.builtin.debug:
    msg: "Building from image file {{ rpi_arch_tgz }}"

#    "{{ lookup('files', 'rpi-img-pt1.sh') }}"

- name: Create new RPI image file
  ansible.builtin.script: >
    rpi-img-pt1.sh
    "{{ rpi_image_name }}"
    "{{ rpi_image_size }}"
    "{{ rpi_mount_point }}"
    "{{ rpi_arch_tgz }}"

  register: rpi_image_result

- name: Set RPI initial host name
  ansible.builtin.copy:
    src: "hostname"
    dest: "{{ rpi_mount_point }}/etc/hostname"
    mode: '0644'
    
- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ rpi_mount_point }}/root/.ssh"
    state: directory
    mode: '0700'

- name: Copy ssh key file to root
  ansible.builtin.copy:
    src: "{{ ansible_ssh_private_key_file }}.pub"
    dest: "{{ rpi_mount_point }}/root/.ssh/authorized_keys"
    mode: '0644'

- name: Deploy base networking profiles
  include_tasks: setup_base_networking.yml
  loop:
    - wired
    - wireless

- name: Disable systemd-networkd service (now using netctl)
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ rpi_mount_point }}/etc/systemd/system/multi-user.target.wants/systemd-networkd.service"
    - "{{ rpi_mount_point }}/etc/systemd/system/network-online.target.wants/systemd-networkd-wait-online.service"
    - "{{ rpi_mount_point }}/etc/systemd/system/sockets.target.wants/systemd-networkd.socket"
    - "{{ rpi_mount_point }}/etc/systemd/system/dbus-org.freedesktop.network1.service"

# We are sending the local hostname to the DHCP server, and not
# requesting one from it
- name: Don't request hostname from DHCP server
  ansible.builtin.lineinfile:
    path: "{{ rpi_mount_point }}/etc/dhcpcd.conf"
    regexp: '^option host_name'
    line: '#option host_name'

- name: Send hostname to DHCP server
  ansible.builtin.lineinfile:
    path: "{{ rpi_mount_point }}/etc/dhcpcd.conf"
    regexp: '^#hostname'
    line: 'hostname'

- name: Set up system setup script
  ansible.builtin.copy:
    src: setup.sh
    dest: "{{ rpi_mount_point }}/root/"
    mode: '0544'

- name: Set up system setup service
  ansible.builtin.copy:
    src: run-aa-once-setup.service
    dest: "{{ rpi_mount_point }}/etc/systemd/system/"
    mode: '0444'

- name: Set default.target
  ansible.builtin.file:
    path: "{{ rpi_mount_point }}/etc/systemd/system/default.target.wants"
    state: directory
    mode: '0755'

- name: Link default setup target
  ansible.builtin.file:
    src: "/etc/systemd/system/run-aa-once-setup.service"
    dest: "{{ rpi_mount_point }}/etc/systemd/system/default.target.wants/run-aa-once-setup.service"
    force: yes
    follow: False
    state: link

- name: Finish new RPI image file
  ansible.builtin.shell:
    cmd: "{{ lookup('template', 'rpi-img-pt2.sh.j2') }}"

- name: debug2
  ansible.builtin.debug:
    var: rpi_image_result.stdout_lines
